config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :report_viewer do
    collection do
      post 'view_report', to: 'report_viewer#view_report'
    end
  end
  resources :teams
  resources :profiles
  resources :notes do
    collection do
      post 'change_team_and_dates', to: 'notes#change_team_and_dates'
    end
  end
  resources :user_settings do
    collection do
      put 'change_password', to: 'user_settings#change_password'
    end
  end
  resources :new_user
  resources :users do
    collection do
      put ':id/reset_password', to: 'users#reset_password'
    end
  end
  resources :analytics do
    collection do
      post 'change_team_and_dates', to: 'analytics#change_team_and_dates'
    end
  end
  resources :sessions do
    collection do
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
  end
  resources :test_runs
  resources :file_uploader do
    collection do
      post 'process_file', to: 'file_uploader#process_file'
      put 'upload', to: 'file_uploader#upload'
    end
  end
  root 'report_viewer#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/error_message.rb
class ErrorMessage < ApplicationRecord
  validates :error_message, presence: true
  has_many :individual_tests
  has_many :notes
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates :feature_name, presence: true
  validates :json_feature_id, presence: true
  has_many :scenarios
  belongs_to :team
end

app/models/individual_test.rb
class IndividualTest < ApplicationRecord
  validates :passed, :inclusion => { :in => [true, false] }
  validates :duration, presence: true
  belongs_to :test_run
  belongs_to :scenario
  belongs_to :error_message, optional: true
  validates :error_message, :presence => true, :unless => :passed
  validates_absence_of :error_message, :if => :passed
  has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  validate :tied_to_either_scenario_or_test_not_both
  validates :note, presence: true
  belongs_to :scenario, optional: true
  belongs_to :individual_test, optional: true
  belongs_to :error_message
  belongs_to :team
  belongs_to :user

  def tied_to_either_scenario_or_test_not_both
    unless scenario.nil?
      unless individual_test.nil?
        errors.add(:base, "If note is attached to a Scenario it must NOT have an attached Individual Test")
      end
    end
    unless individual_test.nil?
      unless scenario.nil?
        errors.add(:base, "If note is attached to an Individual Test it must NOT have an attached Scenario")
      end
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :profile_name, presence: true
  belongs_to :team
  has_many :test_runs
  has_many :users
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  validates :scenario_name, presence: true
  validates :steps, presence: true
  validates :json_scenario_id, presence: true
  belongs_to :feature
  has_many :individual_tests
  has_many :notes
end

app/models/team.rb
class Team < ApplicationRecord
  validates :team_name, presence: true
  has_many :profiles
  has_many :test_runs
  has_many :users
  has_many :notes
  has_many :features
end

app/models/test_run.rb
class TestRun < ApplicationRecord
  validates :test_run_name, presence: true
  validates :time_ran, presence: true
  has_many :individual_tests
  belongs_to :team
  belongs_to :profile, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password_confirmation, presence: true
  validates :username, presence: true
  validates :username, :uniqueness => true
  validates :first_name, presence: true
  validates :last_name, presence: true
  belongs_to :team
  belongs_to :profile, optional: true
  belongs_to :user_type
  has_many :notes
end

app/models/user_type.rb
class UserType < ApplicationRecord
  validates :type_name, presence: true
  has_many :users
end

app/helpers/analytics_helper.rb
module AnalyticsHelper

  def most_failed_scenarios(team, from_date, to_date)
    most_failed_scenarios = {}
    scenarios = Scenario.where(feature: Feature.where(team: team))
    return most_failed_scenarios if scenarios.size.eql? 0
    test_runs = test_runs to_date, from_date
    scenarios.each do |scenario|
      test_count_total = IndividualTest.where(scenario: scenario, test_run: test_runs).size
      tests_count_failed = IndividualTest.where(scenario: scenario, test_run: test_runs, passed: false).size
      test_fail_percent = ((tests_count_failed.to_f / test_count_total.to_f) * 100).to_i
      most_failed_scenarios[scenario.id] = {scenario_name: scenario.scenario_name,
                                             test_fail_percent: test_fail_percent}
    end
    most_failed_scenarios.sort_by {|_key, value| value[:test_fail_percent]}.reverse.to_a
  end

  def longest_running_tests(team, from_date, to_date)
    scenario_durations = {}
    scenarios = Scenario.where(feature: Feature.where(team: team))
    return scenario_durations if scenarios.size.eql? 0
    test_runs = test_runs to_date, from_date
    durations = IndividualTest.where(scenario: scenarios, test_run: test_runs).collect{|test| test.duration}
    average_duration = durations.reduce(0, :+) / durations.size

    scenarios.each do |scenario|
      durations = IndividualTest.where(scenario_id: scenario.id, test_run: test_runs).collect {|test| test.duration}
      duration = durations.reduce(0, :+) / durations.size
      compared_to_average = ((duration.to_f / average_duration.to_f) * 100).to_i
      scenario_durations[scenario.id] = {scenario_name: scenario.scenario_name,
                                          duration: (duration.to_f / 1000000000.0).to_i, compared_to_average: compared_to_average}
    end
    scenario_durations.sort_by {|_key, value| value[:compared_to_average]}.reverse.to_a
  end

  def most_common_errors(team, from_date, to_date)
    most_common_errors = {}
    scenarios = Scenario.where(feature: Feature.where(team: team))
    return most_common_errors if scenarios.size.eql? 0
    test_runs = test_runs to_date, from_date
    error_messages = ErrorMessage.where(id: IndividualTest.where(scenario: scenarios, test_run: test_runs).collect { |test| test.error_message_id })
    error_messages.each do |error_message|
      error_count = IndividualTest.where(error_message_id: error_message.id, test_run: test_runs).size
      most_common_errors[error_message.id] = {error_message: error_message.error_message,
                                               error_count: error_count}
    end


    most_common_errors.sort_by {|_key, value| value[:error_count]}.reverse.to_a
  end

  def test_runs(to_date, from_date)
    to_date += " 00:00:00"
    from_date += " 23:59:59"
    TestRun.where('time_ran Between ? and ?', to_date, from_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/new_user_helper.rb
module NewUserHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    update_session user
    update_to_from_dates
  end

  def log_out
    session.delete(:user_id)
    session.delete(:username)
    session.delete(:first_name)
    session.delete(:last_name)
    session.delete(:user_type)
    session[:profile] = nil
    session[:team] = 1
    update_to_from_dates
  end

  def update_session(user)
    session[:user_id] = user.id
    session[:username] = user.username
    session[:first_name] = user.first_name
    session[:last_name] = user.last_name
    session[:team] = user.team_id
    session[:profile] = user.profile_id
    session[:user_type] = user.user_type_id
  end

  def update_to_from_dates
    session[:from_date] = Date.today.to_datetime.strftime("%Y-%m-%d")
    session[:to_date] = (Date.today - 30).to_datetime.strftime("%Y-%m-%d")
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/test_runs_helper.rb
module TestRunsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/shared/_header.html.erb
<div id="header">
  <%= link_to image_tag("logo.png", border: 0), {:controller => :report_viewer, :action => :index}, id: 'logo' %>

  <div id="log_in_out">
    <% if session[:user_id].nil? %>
      <button id="login_button">Login</button>
      <%= render "shared/login_overlay" %>
  <% else %>
      <%= button_to "Log out", login_sessions_path, method: :delete,  id: 'logout' %>
    <% end %>
  </div>
</div>

app/views/shared/_login_overlay.html.erb
<div id="login_overlay">

  <div id="login_container">
    <div id="user_login">
      <div id="login_error">Invalid username/password combination</div>

      <%= form_tag('/sessions/login') do %>
        <div>Username: <%= text_field_tag :username, '', required: true %></div>
        <div>Password: <%= password_field_tag :password, '', required: true %></div>
        <%= submit_tag "Login", id: 'login_submit' %>
      <% end %>
      <div>
        <button id="create_account_button">Create Account</button>
      </div>
      <div>
        <button id="cancel_login">Cancel</button>
      </div>
    </div>
    <div id="create_account">
      <%= form_tag('/new_user', onsubmit: "validate_new_user_form", id: 'create_account_form') do %>
        <div id="passwords_not_match_error" class="create_user_error">Passwords Don't Match</div>
        <div id="username_used_error" class="create_user_error">Username Already Used</div>
        <div id="user_not_created_error" class="create_user_error">User Not Created</div>
        <div>Username: <%= text_field_tag :username, '', required: true %></div>
        <div>First Name: <%= text_field_tag :first_name, '', required: true %></div>
        <div>Last Name: <%= text_field_tag :last_name, '', required: true %></div>
        <div>Password: <%= password_field_tag :password, '', required: true, id: 'create_user_password' %></div>
        <div>Confirm Password: <%= password_field_tag :password_confirmation, '', required: true %></div>
        <div>Team: <%= select_tag "team", options_from_collection_for_select(@teams, 'id', 'team_name') %></div>
        <%= submit_tag "Create Account", id: 'create_account_submit' %>
      <% end %>
      <button id="cancel_create_account_button">Cancel</button>
    </div>
  </div>
</div>
<% if flash.alert.eql? 'login error' %>
  <script>
      $('#login_overlay').show();
      $('#login_error').show();
  </script>
<% elsif flash.alert.eql? 'username used' %>
  <script>
      $('#login_overlay').show();
      $('#user_login').hide();
      $('#create_account').show();
      $('#username_used_error').show();
  </script>
<% elsif flash.alert.eql? 'user not created' %>
  <script>
      $('#login_overlay').show();
      $('#user_login').hide();
      $('#create_account').show();
      $('#user_not_created_error').show();
  </script>
<% end %>

app/views/shared/_menu.html.erb
<div id="menu">
  <%= link_to 'Reports', {:controller => :report_viewer, :action => :index}, id: 'reports_link', class: "menu_link #{'current_page' if @current_page.eql? :reports}" %>
  <%= link_to 'Analytics', {:controller => :analytics, :action => :index}, id: 'analytics_link', class: "menu_link #{'current_page' if @current_page.eql? :analytics}" %>
  <% unless session[:user_id].nil? %>
    <% unless session[:user_type].eql? 3 %>
      <%= link_to 'Add Report', {:controller => :file_uploader, :action => :index}, id: 'add_report_link', class: "menu_link #{'current_page' if @current_page.eql? :add_reports}" %>
      <% if session[:user_type].eql? 1 %>
        <%= link_to 'Teams', {:controller => :teams, :action => :index}, id: 'teams_link', class: "menu_link #{'current_page' if @current_page.eql? :teams}" %>
        <%= link_to 'Profiles', {:controller => :profiles, :action => :index}, id: 'profiles_link', class: "menu_link #{'current_page' if @current_page.eql? :profiles}" %>
        <%= link_to 'Test Runs', {:controller => :test_runs, :action => :index}, id: 'test_runs_link', class: "menu_link #{'current_page' if @current_page.eql? :test_runs}" %>
      <% end %>
      <%= link_to 'Notes', {:controller => :notes, :action => :index}, id: 'notes_link', class: "menu_link #{'current_page' if @current_page.eql? :notes}" %>
      <% if session[:user_type].eql? 1 %>
        <%= link_to 'Users', {:controller => :users, :action => :index}, id: 'users_link', class: "menu_link #{'current_page' if @current_page.eql? :users}" %>
      <% end %>
    <% end %>
    <%= link_to 'Settings', {:controller => :user_settings, :action => :index}, id: 'settings_link', class: "menu_link #{'current_page' if @current_page.eql? :settings}" %>
  <% end %>
</div>